USE [master]
GO

/****** Object:  Database [OMIdatos]    Script Date: 07/28/2014 23:32:43 ******/
CREATE DATABASE [OMIdatos] ON  PRIMARY 
( NAME = N'OMIdatos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\OMIdatos.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OMIdatos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\OMIdatos_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [OMIdatos] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OMIdatos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OMIdatos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OMIdatos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OMIdatos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OMIdatos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OMIdatos] SET ARITHABORT OFF 
GO

ALTER DATABASE [OMIdatos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OMIdatos] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [OMIdatos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OMIdatos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OMIdatos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OMIdatos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OMIdatos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OMIdatos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OMIdatos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OMIdatos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OMIdatos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OMIdatos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OMIdatos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OMIdatos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OMIdatos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OMIdatos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OMIdatos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OMIdatos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OMIdatos] SET  READ_WRITE 
GO

ALTER DATABASE [OMIdatos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OMIdatos] SET  MULTI_USER 
GO

ALTER DATABASE [OMIdatos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OMIdatos] SET DB_CHAINING OFF 
GO

